---
title: "CHAVA_DGE_Analysis"
author: "Carolina"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, global_options, include=FALSE}
knitr::opts_chunk$set(message=FALSE, tidy.opts=list(width.cutoff=60), tidy=TRUE) 
```
#Set Up

load required packages
```{r, message=FALSE, results='hide'}
library(DESeq2)
library(readxl)
library(dplyr)
library(ggplot2)
library(ggfortify)
library(plotly)
library(BiocManager)
library(EnhancedVolcano)
library("AnnotationDbi")
library("org.Hs.eg.db")
library(EnhancedVolcano)
library(ggvenn)
library(pheatmap)
library(clusterProfiler)
library(enrichplot)
library("biomaRt")
library("tibble")
library(PoiClaClu)
library(pheatmap)
library(RColorBrewer)
library(NOISeq)

library(GGally)
library(PCAtools)
library("enrichR")
library(ggpubr)
```


set up count and condition files

```{r, echo=FALSE}
CHAVAcondition=read_excel("~/Library/CloudStorage/OneDrive-JohnsHopkins/Dr.GIlman/CHAVA_RNAseq/CHAVA_R/CHAVAcondition.xlsx")
CHAVAcounts=read.delim("~/Library/CloudStorage/OneDrive-JohnsHopkins/Dr.GIlman/CHAVA_RNAseq/CHAVA_R/CHAVAcounts.txt",row.names = 1)
CHAVAcountsonly=CHAVAcounts[-c(1:5)]

CHAVAinfo=CHAVAcondition
CHAVAinfo$Infection=as.factor(ifelse(CHAVAinfo$Infection==1,"Pos","Neg"))
CHAVAinfo$Sex=as.factor(ifelse(CHAVAinfo$Sex==1,"F","M"))
CHAVAinfo$ECG=as.factor(CHAVAinfo$ECG)
CHAVAinfo$PCA=as.factor(CHAVAinfo$PCA)
CHAVAinfo$OldECG=as.factor(CHAVAinfo$OldECG)
CHAVAinfo$Cat=as.factor(CHAVAinfo$Cat)
CHAVAinfo$Origin=as.factor(CHAVAinfo$Origin)
CHAVAinfo$Batch=as.factor(CHAVAinfo$Batch)
CHAVAinfo$RIN=as.factor(round(CHAVAinfo$RIN))
#CHAVAinfo$AgeRange=cut(CHAVAinfo$Age,breaks=4) #break up age into factors  "(26.1,38.4]" "(38.4,50.7]" "(50.7,62.9]" "(62.9,75.2]"
CHAVAinfo$AgeRange=cut(CHAVAinfo$Age,breaks=3) #(26.1,42.5], (42.5,58.8], (58.8,75.2]
CHAVAinfo$AgeCategory=CHAVAinfo$AgeRange
levels(CHAVAinfo$AgeCategory)=c("Young", "Mid","Old","Oldest")

#here i subset for patients that have values for the ECG, and I remove B140 since incorrect sex and idk what else might be wrong
ECGs=subset(CHAVAinfo,ECG!="NA")$NovogeneCode
CHAVA_ECG=CHAVAinfo[CHAVAinfo$NovogeneCode %in% c(ECGs),]
CHAVA_ECG=droplevels(CHAVA_ECG)
CHAVA_ECG=subset(CHAVA_ECG,NovogeneCode!="B140")
Counts_ECG=subset(CHAVAcountsonly, select=ECGs)
Counts_ECG=subset(Counts_ECG, select=-B140)
```

remove rRNA counts
```{r}
ensembl=useMart("ENSEMBL_MART_ENSEMBL", host = "https://www.ensembl.org")
ensembl = useDataset("hsapiens_gene_ensembl", mart=ensembl)
rRNAs=biomaRt::getBM(values="rRNA", 
               filters="biotype", 
               attributes=c("ensembl_gene_id", "external_gene_name", "gene_biotype"), 
               mart = ensembl)
Counts_ECG=Counts_ECG[!(row.names(Counts_ECG) %in% rRNAs$ensembl_gene_id),]
```

## PCA

set up a dds object with all possible variable to explore and filter out low-count genes
```{r}
dds_Var=DESeqDataSetFromMatrix(countData = Counts_ECG, colData =CHAVA_ECG, design= ~Sex +PCA + Origin + Cat+ AgeCategory + RIN +  Infection)

keepddsVar= rowSums(counts(dds_Var)>= 10) >=3 #keeps genes with at least 3 samples with 10 counts
dds_Var <- dds_Var[keepddsVar,]
```

vst transform to meet assumptions for PCA analysis. 
```{r}
vst_Var <- vst(dds_Var, blind=FALSE)
testrld_Var=rbind(as.data.frame(assay(vst_Var)[, 1:2]))
#ggplot(testrld_Var, aes(x=B052,y=B083))+ geom_hex(bins = 80) + coord_fixed()
```
```{r, message = FALSE}
rv <- rowVars(assay(vst_Var))
pcagenes <-  order(rv, decreasing=TRUE)[seq_len(min(1000, length(rv)))]
pca <- prcomp(t(assay(vst_Var)[pcagenes,]))
percentVar <- pca$sdev^2 / sum( pca$sdev^2 )

autoplot(pca, data=CHAVA_ECG, colour="Sex", size=4) + theme_classic()
ggsave("~SexPCA.pdf")


autoplot(pca, data=CHAVA_ECG, colour="PCA", size=4) + theme_classic() + scale_color_manual(values=c("purple","darkgrey"))
ggsave("~BatchEffect.pdf")

ggpairs(pca$x, columns = 1:5, aes(colour=CHAVA_ECG$Sex), upper =list(continuous= "blank"), diag = list(continuous = wrap("densityDiag",alpha=0.5)),lower = list(continuous = wrap("points", alpha = 0.9, size=0.6)))


ggpairs(pca$x, columns = 1:5, aes(colour=CHAVA_ECG$Infection), upper =list(continuous= "blank"),diag = list(continuous = wrap("densityDiag",alpha=0.5)),legend=c(2,1),lower = list(continuous = wrap("points", alpha = 0.9, size=0.7))) + 
  scale_color_manual(values=c("#4349e8","#f5474a"))+ 
  scale_fill_manual(values=c("#4349e8","#f5474a"))+ theme_bw() + labs(colour="Infection Status")
ggsave("~Infection.pdf")

ggpairs(pca$x, columns = 1:5, aes(colour=CHAVA_ECG$Origin), upper =list(continuous= "blank"),diag = list(continuous = wrap("densityDiag",alpha=0.5)),legend=c(2,1),lower = list(continuous = wrap("points", alpha = 0.9, size=0.7))) + 
  scale_color_manual(values=c("#DE8333","#1c9470")) +
  scale_fill_manual(values=c("#DE8333","#1c9470")) +theme_bw() + labs(colour="Origin")
ggsave("~Origin.pdf")

ggpairs(pca$x, columns = 1:5, aes(colour=CHAVA_ECG$Cat), upper =list(continuous= "blank"),diag = list(continuous = wrap("densityDiag",alpha=0.5)),legend=c(2,1),lower = list(continuous = wrap("points", alpha = 0.9, size=0.7))) + 
  scale_color_manual(values=c("#0fbab7","#1b804f","#6e016b")) +
  scale_fill_manual(values=c("#0fbab7","#1b804f","#6e016b")) +theme_bw() +  labs(colour="Heart Failure")
ggsave("~AHA_Category.pdf")

ggpairs(pca$x, columns = 1:5, aes(colour=CHAVA_ECG$AgeCategory), upper =list(continuous = "blank"),diag = list(continuous = wrap("densityDiag",alpha=0.5)),legend=c(2,1),lower = list(continuous = wrap("points", alpha = 0.9, size=0.7))) + theme_bw() + labs(colour="AgeCategory")
ggsave("~AgeCategory.pdf")


phenoCols=list(Infection=c(Neg="#4349e8",Pos="#f5474a"),Origin=c(CentralAm="#DE8333",Bolivia="#1c9470"),Cat=c(A="#0fbab7",B="#6e016b"))

```

# A vs B by infection status (excluding A2)

## Postive
```{r}
CHAVA_ECG_AB_Pos=subset(CHAVA_ECG, Cat!="A2"&Infection=="Pos")
CHAVA_ECG_AB_Pos=droplevels(CHAVA_ECG_AB_Pos)
Counts_ECG_AB_Pos=subset(Counts_ECG, select=CHAVA_ECG_AB_Pos$NovogeneCode)
```

### DGE
```{r}

ddsAB_Pos=DESeqDataSetFromMatrix(countData = Counts_ECG_AB_Pos, colData =CHAVA_ECG_AB_Pos, design= ~PCA + Sex +  Cat)
keepddsAB_Pos= rowSums(counts(ddsAB_Pos)>= 10) >=3 #keeps genes with at least 3 samples with 10 counts
ddsAB_Pos <- ddsAB_Pos[keepddsAB_Pos,]
ddsAB_Pos=DESeq(ddsAB_Pos) #normalizes, estimates dispersion and fits glm

result_AB_Pos=results(ddsAB_Pos,alpha = 0.1,contrast=c("Cat", "B", "A")) 
summary(result_AB_Pos)
Sig_AB_Pos=subset(result_AB_Pos, padj < 0.1)
```

annotate results
```{r}

annot_AB_Pos <- getBM(attributes=c('ensembl_gene_id', 'external_gene_name'), 
               filters = "ensembl_gene_id", 
               values = rownames(result_AB_Pos), 
               mart = ensembl)

annot_AB_Pos<- as.data.frame(result_AB_Pos) %>% 
  rownames_to_column("ensembl_gene_id") %>% 
  left_join(annot_AB_Pos, "ensembl_gene_id") %>% 
  rename(log2FC=log2FoldChange, FDR=padj)


SigAnnot_AB_Pos = subset(annot_AB_Pos, FDR < 0.1)
SigAnnot_AB_Pos[order(SigAnnot_AB_Pos$log2FC), ]

#write.csv(SigAnnot_AB_Pos,"All_AB_Posv.csv")
```

